os: osx
osx_image:
  - xcode10
  - xcode11
  - xcode12

install:
  - brew list
  - brew install python
  # gdal breaks pip3 update
  - brew uninstall postgis gdal
  - pip3 install ansible

script:
  - ansible-playbook macdev.yml --syntax-check
  - >
    cp host_vars/localhost-example.yml host_vars/localhost.yml;
    sed -i '' -e 's/role_ssh: yes/role_ssh: no/' host_vars/localhost.yml
  # run the playbook
  - ansible-playbook macdev.yml
  # run again -> expect no change
  - >
    ansible-playbook macdev.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)