os: osx

jobs:
  include:
    - osx_image: xcode10.1
      # swiftlint requires xcode10.2
      env: BREW_UNINSTALL="postgis gdal swiftlint"
    - osx_image: xcode11.3
      env: BREW_UNINSTALL="postgis gdal"
    - osx_image: xcode12

install:
  - brew list
  - brew install python
  # gdal breaks pip3 update
  - [ -n "$BREW_UNINSTALL" ] && brew uninstall $BREW_UNINSTALL
  - pip3 install ansible

script:
  - ansible-playbook macdev.yml --syntax-check
  - cp host_vars/localhost-example.yml host_vars/localhost.yml
  # run the playbook
  - ansible-playbook macdev.yml
  # run again -> expect no change
  - >
    ansible-playbook macdev.yml
    | grep -e 'changed=0.*failed=0' -e '^changed'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)