---
- name:
  hosts: localhost
  environment:
    BASH_ENV: "~/.profile" # required to load the local environment (PATH etc.)
  roles:
    - { role: env }
    - { role: ssh, when: role_ssh }
    - { role: pip, when: role_pip }
    - { role: app, when: role_app }
