---

# - name: Check pip version

- name: Upgrade packages
  shell: pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U 
  register: pip_upgrade
  failed_when: pip_upgrade.rc == 1
  changed_when: pip_upgrade.stdout_lines|length > 0

- name: Install packages
  shell: pip3 install {{ item.name }}
  args:
    creates: "{{ item.path }}"
  with_items: "{{ pip_packages }}"
  when: pip_packages|default([])|length > 0 

