---

# - name: Check pip version
- name: List outdated packages
  shell: pip3 list --outdated --format=freeze
  register: pip3-outdated
- debug: var=pip3-outdated.stdout_lines

- name: Upgrade packages
  shell: pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | grep -v '\({{pip3_omit_upgrade}}\)' | xargs -n1 pip3 install -U
  args:
    executable: /bin/bash
  register: pip_upgrade
  failed_when: pip_upgrade.rc == 1
  changed_when: pip_upgrade.stdout_lines|length > 0

- name: Install packages
  shell: pip3 install {{ item.name }}
  args:
    executable: /bin/bash
    creates: "{{ item.path }}"
  with_items: "{{ pip_packages }}"

