---

# - name: Check pip version

- name: Install+Upgrade packages
  shell: pip3 install -U {{ item.name }}
  args:
    executable: /bin/bash
    creates: "{{ item.path }}"
  with_items: "{{ pip_packages }}"

