---

- name: Upgrade packages
  shell: pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | grep -v '\({{pip_omit_upgrade}}\)' | xargs -n1 pip3 install -U
  args:
    executable: /bin/bash
  register: pip_upgrade
  failed_when: pip_upgrade.rc != 0
  changed_when: pip_upgrade.stdout|contains("Successfully installed")
- debug: var=pip_upgrade.stdout_lines
  when: pip_upgrade is changed

- name: Install packages
  pip:
    name: "{{ pip_packages|map(attribute='name')|flatten }}"
    state: latest
    executable: pip3
