---

- name: SSH directory permissions
  file: path=$HOME/.ssh owner={{ ansible_user_id }} group={{ user_group }} mode=0755

- name: SSH key permissions
  file: path=$HOME/.ssh/id_rsa owner={{ ansible_user_id }} group={{ user_group }} mode=0600
