---

- name: SSH directory permissions
  file: path=$HOME/.ssh owner={{ ansible_user_id }} group={{ user_group }} mode=0700

- name: SSH key permissions
  shell: |
    chown {{ ansible_user_id }}:{{ user_group }} .ssh/id*
    chmod 600 $HOME/.ssh/id*
  changed_when: false
