---
- name: Set hostname
  shell: |
    scutil --set ComputerName {{ network.hostname }};
    scutil --set HostName {{ network.hostname }}
    scutil --set LocalHostName {{ network.hostname }}
    defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string {{ network.hostname|lower }}
  become: yes
  become_user: "root"
  when: network.hostname is defined
