---

- name: Check for homebrew
  stat: path=/usr/local/bin/brew
  register: homebrew

- name: Homebrew needs manual installation
  debug: msg='Install homebrew manually (https://brew.sh) /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: homebrew.stat.exists == false
  failed_when: homebrew.stat.exists == false

- name: Setup brew for multiple users
  shell: (cd /usr/local; chmod +a "group:{{ user_group }} allow list,add_file,search,add_subdirectory,delete_child,chown,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" Homebrew Caskroom Cellar bin && chgrp -vR {{ user_group }} Homebrew Caskroom Cellar bin && chmod -R g+rwX Homebrew Caskroom Cellar bin)
  args:
    executable: /bin/bash
  register: brew_chmod
  failed_when: brew_chmod.rc == 1
  changed_when: false
  when: brew_multiuser|bool == true

- name: Update homebrew
  homebrew:
    update_homebrew: yes

- name: Upgrade homebrew packages
  homebrew:
    upgrade_all: yes
  when: not brew_skip_upgrade|default(false)

- name: Install/Update python + ansible
  shell: brew install python; pip3 install -U ansible
  when: '"python" in brew_packages|map(attribute="name")|flatten'
  register: python_update
  failed_when: python_update.rc != 0
  changed_when: 'not python_update.stdout is search("already up-to-date: ansible")'

- name: Install/Update brew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ brew_packages|map(attribute='name')|flatten }}"
  when: brew_packages[0] is defined

- name: Upgrade homebrew casks
  homebrew_cask:
    upgrade_all: yes
  when: not brew_cask_skip_upgrade|default(false)

- name: Install brew cask packages
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ brew_cask_packages|map(attribute='name')|flatten }}"
  when: brew_cask_packages[0] is defined

