---

- name: Check for homebrew
  shell: echo "$HOMEBREW_PREFIX"
  register: homebrew_prefix

- name: Set vars
  set_fact:
    brew_installed: true
    brew_bin: "{{ homebrew_prefix.stdout }}/bin"
    brew_sbin: "{{ homebrew_prefix.stdout }}/sbin"
  when: homebrew_prefix.stdout != ""

- name: Homebrew needs manual installation
  debug: msg='Install homebrew manually (https://brew.sh) /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: not brew_installed
  failed_when: not brew_installed

- name: Upgrade homebrew
  shell: brew upgrade
  register: brew_upgrade
  changed_when: brew_upgrade.stdout|length > 1 and not brew_upgrade.stdout|regex_search("No changes to formulae.")

- name: Install brew packages
  shell: brew install {{ item.name }}
  args:
    creates: "{{ item.path }}"
  with_items: "{{ brew_packages }}"
  when: brew_packages[0] is defined

- name: Upgrade homebrew casks
  shell: brew upgrade --cask
  register: cask_upgrade
  changed_when: cask_upgrade.stdout_lines|length > 1

- name: Install brew cask packages
  shell: brew install --cask {{ item.name }}
  args:
    creates: "{{ item.path }}"
  with_items: "{{ brew_cask_packages }}"
  when: brew_cask_packages[0] is defined

