---

- name: Check for homebrew
  stat: path=/usr/local/bin/brew
  register: homebrew

- name: Homebrew needs manual installation
  debug: msg='Install homebrew manually (https://brew.sh) /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  when: homebrew.stat.exists == false
  failed_when: homebrew.stat.exists == false

- name: Setup brew for multiple users
  shell: (cd /usr/local; chmod +a "group:admin allow list,add_file,search,add_subdirectory,delete_child,chown,readattr,writeattr,readextattr,writeextattr,readsecurity,file_inherit,directory_inherit" Homebrew Caskroom Cellar bin && chgrp -vR {{ user_group }} Homebrew Caskroom Cellar bin && chmod -R g+rwX /usr/local/Homebrew /usr/local/Caskroom /usr/local/Cellar /usr/local/bin)
  args:
    executable: /bin/bash
  register: brew_chmod
  failed_when: brew_chmod.rc == 1
  changed_when: false
  when: brew_multiuser|bool == true

- name: Upgrade homebrew
  shell: brew upgrade
  register: brew_upgrade
  changed_when: brew_upgrade.stdout|length > 1

- name: Install brew packages
  shell: brew install {{ item.name }}
  args:
    executable: /bin/bash
    creates: "{{ item.path }}"
  with_items: "{{ brew_packages }}"
  when: brew_packages[0] is defined

- name: Upgrade homebrew casks
  shell: brew cask upgrade
  register: cask_upgrade
  changed_when: cask_upgrade.stdout_lines|length > 1

- name: Install brew cask packages
  shell: brew cask install {{ item.name }}
  args:
    executable: /bin/bash
    creates: "{{ item.path }}"
  with_items: "{{ brew_cask_packages }}"
  when: brew_cask_packages[0] is defined

