---
- name: Check vars
  debug: msg="`config` is not defined"
  failed_when: config is not defined

- name: Set Keyboard
  shell: defaults write -g {{ item.key }} -int {{ item.int }}
  with_items: "{{ config.keyboard }}"
  when: config.keyboard is defined and item.int is defined

- name: Set default Finder view
  shell: defaults write com.apple.finder FXPreferredViewStyle -string {{ config.finder.defaultView }}
  when: config.finder is defined and config.finder.defaultView is defined

- name: Configure Dock
  shell: |
    defaults write com.apple.dock {{ item.key }} \
    {{ "-int "+item.int|string if item.int is defined }} \
    {{ "-float "+item.float|string if item.float is defined }} \
    {{ "-bool "+item.bool|string if item.bool is defined }} \
    {{ "-string "+item.string if item.string is defined }}
  with_items: "{{ config.dock }}"
  register: dock_config
  when: config.dock is defined

- name: Restart Dock
  shell: killall Dock
#  become: yes
#  become_user: root
  when: dock_config is changed