---

# roles
role_ssh: yes
role_sys: yes
role_cfg: yes
role_ansible: true
role_pip: yes
role_brew: yes
role_app: no

config_url: "https://raw.githubusercontent.com/DrPsychick/macdev/master/host_vars/localhost-drpsychick-trinity.yml"

system:
  hostname: trinity
  # sudo systemsetup -help
  systemsetup:
    - { key: "-setrestartfreeze", value: "on" }
    #- { key: "-setcomputersleep", value: "5" }
    # - { key: "-setdisplaysleep", value: "3" }
  # domain = /Library/Preferences/com.apple.loginwindow
#  loginwindow:
#    - { key: "AdminHostInfo", value: "HostName" }
#    - { key: "GuestEnabled", value: "0" }
  generic:
    - { domain: "/Library/Preferences/com.apple.loginwindow", key: "AdminHostInfo", type: string, value: "HostName" }
    - { domain: "/Library/Preferences/com.apple.loginwindow", key: "GuestEnabled", type: bool, value: 0 }
  timemachine:
    destination: "smb://snoopy@neb%28TimeMachine%29._smb._tcp.local./macbackups"
    exclusions:
      - /Users/Shared/SharedDocs
      - /Users/muc/Documents
      - /Users/muc/Library/Application Support/MobileSync
      - /Users/muc/Library/Application Support/rancher-desktop
      - /Users/muc/Library/Caches
      - /Users/muc/Library/Containers/com.docker.docker
      - /Users/muc/Library/Developer/CoreSimulator/Caches
      - /Users/muc/Library/iTunes/iPhone Software Updates
      - /Users/muc/Library/iTunes/iPad Software Updates
      - /Users/muc/work/git
      - /Users/pascal/Library/Application Support/rancher-desktop
      - /Users/pascal/Library/Caches
      - /Users/pascal/Library/Developer/CoreSimulator/Caches
      - /Users/pascal/work/git
      - /Users/snoopy/Documents
      - /Users/snoopy/Library/Caches
      - /Users/snoopy/Library/Mobile Documents
#      - /Users/dlazy/CurseForge
#      - /Users/dlazy/Documents

# Per user configuration
config:
  # domain = NSGlobalDomain
  global:
    - { key: "InitialKeyRepeat", type: int, value: 20 }
    - { key: "KeyRepeat", type: int, value: 1 }
  generic:
    - { domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores", type: bool, value: 1 }
    - { domain: "com.apple.Safari", key: "IncludeDevelopMenu", type: bool, value: 1 }
    - { domain: "com.apple.Safari", key: "WebKitDeveloperExtrasEnabledPreferenceKey", type: bool, value: 1 }
    - { domain: "com.apple.Safari", key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled", type: bool, value: 1 }
    - { domain: "com.apple.gamed",  key: "Disabled", type: bool, value: 1 }
    # touchpad configuration
    - { domain: "com.apple.AppleMultitouchTrackpad", key: "Clicking", type: bool, value: 1 }
    # menu clock configuration
    - { domain: "com.apple.menuextra.clock", key: "DateFormat", type: string, value: "EEE d MMM 'at' HH:mm:ss" }
    - { domain: "com.apple.menuextra.clock", key: "ShowDayOfWeek", type: int, value: 0 }
    - { domain: "com.apple.menuextra.clock", key: "Show24Hour", type: int, value: 1 }
    - { domain: "com.apple.menuextra.clock", key: "ShowSeconds", type: int, value: 1 }
    - { domain: "com.apple.controlcenter", key: "NSStatusItem\\ Visible\\ Bluetooth", type: int, value: 1 } # requires restart of ???
  # domain = com.apple.finder
  finder:
    - { key: "FXPreferredViewStyle", type: string, value: "Nlsv" }
  # domain = com.apple.dock
  dock:
    - { key: "magnification", type: bool, value: 1 }
    - { key: "tilesize", type: int, value: 32 }
    - { key: "largesize", type: int, value: 128 }
    - { key: "autohide", type: bool, value: 1 }
    - { key: "showhidden", type: bool, value: 1 }
    - { key: "wvous-tl-corner", type: int, value: 5 }
    - { key: "wvous-tl-modifier", type: int, value: 0 }
    - { key: "wvous-tr-corner", type: int, value: 11 }
    - { key: "wvous-tr-modifier", type: int, value: 0 }
    - { key: "wvous-bl-corner", type: int, value: 3 }
    - { key: "wvous-bl-modifier", type: int, value: 0 }
    - { key: "wvous-br-corner", type: int, value: 2 }
    - { key: "wvous-br-modifier", type: int, value: 0 }
    - { key: "expose-animation-duration", type: float, value: 0.5 }

## user files and templates:
# overwrite: replace file on target, if it exists
# source: "interactive" or "login"

files: []
  #- { name: "file-example", path: "$HOME/file-example", overwrite: true, shell: false }

templates: []

# instead of copying a file or template, you can define aliases one by one
shell_aliases:
  - { name: "updatemac", cmd: "(cd ~/work/git/drpsychick/macdev; {{ 'echo \"password for sudo:\"; sudo echo;' if role_sys }} ansible-playbook macdev.yml)" }
  - { name: "rancherVM", cmd: 'LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0' }
  - { name: "fixvpn", cmd: "sudo route delete -host 85.190.148.133 192.168.1.1; sudo route add -host 85.190.148.133 192.168.1.1" }
  - { name: "ll", cmd: "ls -lah" }

ansible_collections:
  - { name: community.general }
  # see https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
  - { name: community.docker }
  - { name: community.kubernetes } # , version: "", source: "" }

brew_taps: []
#  - hashicorp/tap
#  - drpsychick/sensei

brew_packages:
  - { name: asciinema, path: "{{brew_bin}}/asciinema" }
  - { name: direnv, path: "{{brew_bin}}/direnv" }
  - { name: findutils, path: "{{brew_bin}}/gfind" }
  - { name: glances, path: "{{brew_bin}}/glances" }
  - { name: gnupg, path: "{{brew_bin}}/gpg" }
  - { name: go, path: "{{brew_bin}}/go" }
  - { name: golangci-lint, path: "{{brew_bin}}/golangci-lint" }
  - { name: goreleaser, path: "{{brew_bin}}/goreleaser" }
  - { name: gron, path: "{{brew_bin}}/gron" }
  #- { name: helm, path: "{{brew_bin}}/helm" } # conflicts with Rancher Desktop
  - { name: hub, path: "{{brew_bin}}/hub" }
  - { name: imagemagick, path: "{{brew_bin}}/magick" }
  - { name: jq, path: "{{brew_bin}}/jq" }
  - { name: k3d, path: "{{brew_bin}}/k3d" }
  - { name: kubeseal, path: "{{brew_bin}}/kubeseal" }
  - { name: kustomize, path: "{{brew_bin}}/kustomize" }
  - { name: molecule, path: "{{brew_bin}}/molecule" }
  - { name: mtr, path: "{{brew_sbin}}/mtr" }
  - { name: node, path: "{{brew_bin}}/node" }
  - { name: pinentry-mac, path: "{{brew_bin}}/pinentry-mac" }
  - { name: pre-commit, path: "{{brew_bin}}/pre-commit" }
  - { name: pwgen, path: "{{brew_bin}}/pwgen" }
  - { name: qemu, path: "{{brew_bin}}/qemu-img" }
  - { name: drpsychick/sensei/sensei, path: "{{brew_bin}}/sensei" }
  - { name: smartmontools, path: "{{brew_bin}}/smartctl" }
  - { name: telegraf, path: "{{brew_bin}}/telegraf" }
  - { name: tenv, path: "{{brew_bin}}/tenv" }
  - { name: hashicorp/tap/vault, path: "{{brew_bin}}/vault" }
  - { name: wakeonlan, path: "{{brew_bin}}/wakeonlan" }
  - { name: watch, path: "{{brew_bin}}/watch" }
  - { name: yamale, path: "{{brew_bin}}/yamale" }
  - { name: yamllint, path: "{{brew_bin}}/yamllint" }

brew_cask_packages:
  - { name: 1password, path: "/Applications/1Password.app" }
  - { name: 1password-cli, path: "{{brew_bin}}/op" }
  #- { name: atom, path: "/Applications/Atom.app" }
  - { name: curseforge, path: "/Applications/CurseForge.app" }
  #- { name: docker, path: /Applications/Docker.app }
  - { name: deepl, path: "/Applications/Deepl.app" }
  - { name: discord, path: "/Applications/Discord.app" }
  - { name: drawio, path: "/Applications/draw.io.app" }
  - { name: element, path: "/Applications/element.app" }
  - { name: finicky, path: "/Applications/finicky.app" }
  #- { name: qdslrdashboard, path: "/Applications/qDslrDashboard.app" }
  - { name: gimp, path: "/Applications/GIMP.app" }
  - { name: goland, path: "/Applications/GoLand.app" }
  - { name: google-chrome, path: "/Applications/Google Chrome.app" }
  - { name: google-cloud-sdk, path: "/opt/homebrew/bin/gcloud" }
  - { name: google-drive, path: "/Applications/Google Drive.app" }
  - { name: iterm2, path: "/Applications/iTerm.app" }
  - { name: krita, path: "/Applications/krita.app" }
  #- { name: libreoffice, path: "/Applications/LibreOffice.app" }
  - { name: macpass, path: "/Applications/MacPass.app" }
  - { name: macs-fan-control, path: "/Applications/Macs Fan Control.app" }
  #- { name: mattermost, path: "/Applications/Mattermost.app" }
  #- { name: microsoft-teams, path: "/Applications/Microsoft Teams.app" }
  - { name: minecraft, path: "/Applications/Minecraft.app" }
  #- { name: mindforger, path: "/Applications/mindforger.app" }
  - { name: monitorcontrol, path: "/Applications/MonitorControl.app" }
  #- { name: moom, path: "/Applications/Moom.app" }
  - { name: moonlight, path: "/Applications/Moonlight.app" }
  - { name: nordvpn, path: "/Applications/NordVPN.app" }
  #- { name: obs, path: "/Applications/OBS.app" }
  #- { name: obs-virtualcam, path: "{{ brew_prefix }}/Caskroom/obs-virtualcam" }
  - { name: obsidian, path: "/Applications/Obsidian.app" }
  #- { name: openoffice, path: /Applications/OpenOffice.app }
  - { name: postman, path: "/Applications/Postman.app" }
  - { name: pycharm, path: "/Applications/PyCharm.app" }
  #- { name: pycharm-ce, path: "/Applications/PyCharm CE.app" }
  #- { name: qsync-client, path: "/Applications/QSync Client.app" }
  - { name: rancher, path: "/Applications/Rancher Desktop.app" }
  - { name: slack, path: "/Applications/Slack.app" }
  - { name: spectacle, path: "/Applications/Spectacle.app" }
  - { name: spotify, path: "/Applications/Spotify.app" }
  - { name: sweet-home3d, path: "/Applications/Sweet Home 3D.app" }
  - { name: threema, path: "/Applications/Threema.app" }
  - { name: tunnelblick, path: "/Applications/Tunnelblick.app" }
  - { name: utm, path: "/Applications/UTM.app" }
  - { name: vlc, path: "/Applications/VLC.app" }
  - { name: vnc-viewer, path: "/Applications/VNC Viewer.app" }

pip_packages: []
#  - { name: yamale, path: "{{pip_bin}}/yamale" }
#  - { name: kubernetes, path: "/lib/python3.9/site-packages/kubernetes" }
#  - { name: ansible, path: "{{pip_bin}}/ansible" }
#  - { name: awscli, path: "{{pip_bin}}/aws" }

# supports .zip and .dmg
app_packages:
