---

# roles
role_ssh: yes
role_sys: no
role_cfg: yes
role_ansible: true
role_pip: yes
role_brew: no
role_app: no

config_url: "https://raw.githubusercontent.com/DrPsychick/macdev/master/host_vars/localhost-drpsychick-neo-pascal.yml"

# Per user configuration
config:
  # domain = NSGlobalDomain
  global:
    - { key: "InitialKeyRepeat", type: int, value: 20 }
    - { key: "KeyRepeat", type: int, value: 1 }
  generic:
    - { domain: "com.apple.desktopservices", key: "DSDontWriteNetworkStores", type: bool, value: 1 }
    - { domain: "com.apple.Safari", key: "IncludeDevelopMenu", type: bool, value: 1 }
    - { domain: "com.apple.Safari", key: "WebKitDeveloperExtrasEnabledPreferenceKey", type: bool, value: 1 }
    - { domain: "com.apple.Safari", key: "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled", type: bool, value: 1 }
    - { domain: "com.apple.gamed",  key: "Disabled", type: bool, value: 1 }
    # touchpad configuration
    - { domain: "com.apple.AppleMultitouchTrackpad", key: "Clicking", type: bool, value: 1 }
    # menu clock configuration
    - { domain: "com.apple.menuextra.clock", key: "DateFormat", type: string, value: "EEE d MMM 'at' HH:mm:ss" }
    - { domain: "com.apple.menuextra.clock", key: "ShowDayOfWeek", type: int, value: 0 }
    - { domain: "com.apple.menuextra.clock", key: "Show24Hour", type: int, value: 1 }
    - { domain: "com.apple.menuextra.clock", key: "ShowSeconds", type: int, value: 1 }
    - { domain: "com.apple.controlcenter", key: "NSStatusItem\\ Visible\\ Bluetooth", type: int, value: 1 } # requires restart of ???
    # do not rearrange spaces/desktops
    - { domain: "com.apple.dock", key: "mru-spaces", type: bool, value: 0 }
    # domain = com.apple.finder
  finder:
    - { key: "FXPreferredViewStyle", type: string, value: "Nlsv" }
  # domain = com.apple.dock
  dock:
    - { key: "magnification", type: bool, value: 1 }
    - { key: "tilesize", type: int, value: 32 }
    - { key: "largesize", type: int, value: 128 }
    - { key: "autohide", type: bool, value: 1 }
    - { key: "showhidden", type: bool, value: 1 }
    - { key: "wvous-tl-corner", type: int, value: 5 }
    - { key: "wvous-tl-modifier", type: int, value: 0 }
    - { key: "wvous-tr-corner", type: int, value: 11 }
    - { key: "wvous-tr-modifier", type: int, value: 0 }
    - { key: "wvous-bl-corner", type: int, value: 3 }
    - { key: "wvous-bl-modifier", type: int, value: 0 }
    - { key: "wvous-br-corner", type: int, value: 2 }
    - { key: "wvous-br-modifier", type: int, value: 0 }
    - { key: "expose-animation-duration", type: float, value: 0.5 }

sync_files:
  - { file: "gitconfig", source: "1password", op: "a8n-home/macdev templates/gitconfig" }
  - { file: "gitconfig-allowed_signers", source: "1password", op: "a8n-home/macdev templates/gitconfig-allowed_signers" }
  - { file: "gitconfig-private", source: "1password", op: "a8n-home/macdev templates/gitconfig-private" }
  - { file: "gitconfig-github", source: "1password", op: "a8n-home/macdev templates/gitconfig-github" }
  - { file: "gitconfig-gitlab", source: "1password", op: "a8n-home/macdev templates/gitconfig-gitlab" }
  - { file: "gitconfig-work1", source: "1password", op: "a8n-home/macdev templates/gitconfig-work1" }
  - { file: "gitconfig-work2", source: "1password", op: "a8n-home/macdev templates/gitconfig-work2" }
  - { file: "gitconfig-work3", source: "1password", op: "a8n-home/macdev templates/gitconfig-work3" }
  - { file: "registry-config.json", source: "1password", op: "a8n-home/registry config/registry-config.json" }
sync_templates: []

## user files and templates:
# overwrite: replace file on target, if it exists
# source: "interactive" or "login"

files:
  - { name: "git-check-user.sh", path: "$HOME/bin/git-check-user.sh", overwrite: true, mode: 0755 }
  - { name: "git-check-diff.sh", path: "$HOME/bin/git-check-diff.sh", overwrite: true, mode: 0755 }
  - { name: "gitconfig", path: "$HOME/.gitconfig", overwrite: true }
  - { name: "gitconfig-allowed_signers", path: "$HOME/.gitconfig-allowed_signers", overwrite: true }
  - { name: "gitconfig-private", path: "$HOME/.gitconfig-private", overwrite: true }
  - { name: "gitconfig-github", path: "$HOME/.gitconfig-github", overwrite: true }
  - { name: "gitconfig-gitlab", path: "$HOME/.gitconfig-gitlab", overwrite: true }
  - { name: "gitconfig-work1", path: "$HOME/.gitconfig-work1", overwrite: true }
  - { name: "gitconfig-work2", path: "$HOME/.gitconfig-work2", overwrite: true }
  - { name: "gitconfig-work3", path: "$HOME/.gitconfig-work3", overwrite: true }
  - { name: "registry-config.json", path: "$HOME/Library/Preferences/helm/registry/config.json", overwrite: true }
templates:
  - { name: "myfunctions.sh", path: "$HOME/bin/myfunctions.sh", overwrite: true, source: "interactive" }
  - { name: "home-functions.sh", path: "$HOME/bin/home-functions.sh", overwrite: true }
  - { name: "finicky.js", path: "$HOME/.finicky.js", overwrite: true }

shell_aliases:
  - { name: "updatemac", cmd: "(cd ~/work/git/drpsychick/macdev; {{ 'echo \"password for sudo:\"; sudo echo;' if role_sys }} ansible-playbook macdev.yml)" }
  - { name: "rancherVM", cmd: 'LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima" "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0' }
  - { name: "fixvpn", cmd: "sudo route delete -host 85.190.148.133 192.168.1.1; sudo route add -host 85.190.148.133 192.168.1.1" }
  - { name: "ykssh", cmd: "killall gpg-agent; export GPG_TTY=$(tty); export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket); gpgconf --launch gpg-agent" }
  - { name: "ll", cmd: "ls -lah" }
  - { name: "kubectl", cmd: "kubecolor" }

ansible_collections:
  - { name: community.general }
  # see https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#install-multiple-collections-with-a-requirements-file
  - { name: community.docker }
  - { name: community.kubernetes } # , version: "", source: "" }

pip_packages: []
#  - { name: yamale, path: "{{pip_bin}}/yamale" }
#  - { name: kubernetes, path: "/lib/python3.9/site-packages/kubernetes" }
#  - { name: ansible, path: "{{pip_bin}}/ansible" }
#  - { name: awscli, path: "{{pip_bin}}/aws" }

# supports .zip and .dmg
app_packages:
